name: CI/CD Docker

on:
  push:
    branches:
      - main # ou la branche que vous souhaitez déclencher

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2

      - name: Connexion à Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build de l'image Docker
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t aymanesgi/weeesh:latest .

      - name: Push de l'image Docker
        run: docker push yourusername/yourimage:latest

      - name: Nettoyage
        run: docker buildx stop
